### ISSUE TITLE
Announce the initiative to talk-ph list for wider community discussion and inputs

### ISSUE THREAD

**Issue by maning** [OSMPH/Tabang-AI#1]
- [x] Post as a wikipage under Philippines in OSM wiki:`https://wiki.openstreetmap.org/wiki/Philippines/Tabang-AI`
- [x] Announce in talk-ph list
- [x] OSM diary

**Comment by maning** [comment]
Project brief is now posted in the OSM wiki: https://wiki.openstreetmap.org/wiki/Philippines/Tabang-AI

**Comment by maning** [comment]
OSM Diary by @govvin : https://www.openstreetmap.org/user/GOwin/diary/390452

**Comment by seav** [comment]
Announced on the talk-ph and talk mailing lists and on Facebook:
- https://lists.openstreetmap.org/pipermail/talk-ph/2019-August/006457.html
- https://lists.openstreetmap.org/pipermail/talk/2019-August/083104.html
- https://www.facebook.com/OSMPH/photos/a.10151205842257597/10157227627622597/
- https://www.facebook.com/groups/osmph/permalink/919811535022892/
